apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- provider-components-kubeadm.yaml
- provider-components-cluster-api.yaml
- provider-components-vsphere.yaml
- capv_manager_bootstrap_credentials.yaml
patchesStrategicMerge:
- cabpk_manager_patches.yaml
- capi_manager_patches.yaml
- capv_manager_patches.yaml
- manager_tolerations_patch.yaml
