---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.20.0
  name: vsphereclustertemplates.vmware.infrastructure.cluster.x-k8s.io
spec:
  group: vmware.infrastructure.cluster.x-k8s.io
  names:
    categories:
    - cluster-api
    kind: VSphereClusterTemplate
    listKind: VSphereClusterTemplateList
    plural: vsphereclustertemplates
    singular: vsphereclustertemplate
  scope: Namespaced
  versions:
  - deprecated: true
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: VSphereClusterTemplate is the Schema for the vsphereclustertemplates
          API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec is the desired state of VSphereClusterTemplate.
            properties:
              template:
                description: template defines the desired state of VSphereClusterTemplate.
                properties:
                  spec:
                    description: spec is the desired state of VSphereClusterTemplateResource.
                    properties:
                      controlPlaneEndpoint:
                        description: controlPlaneEndpoint represents the endpoint
                          used to communicate with the control plane.
                        properties:
                          host:
                            description: host is the hostname on which the API server
                              is serving.
                            maxLength: 512
                            type: string
                          port:
                            description: port is the port on which the API server
                              is serving.
                            format: int32
                            type: integer
                        type: object
                      network:
                        description: network defines the network configuration for
                          the cluster with different network providers.
                        minProperties: 1
                        properties:
                          nsxVPC:
                            description: nsxVPC defines the configuration when the
                              network provider is NSX-VPC.
                            minProperties: 1
                            properties:
                              createSubnetSet:
                                description: createSubnetSet is a flag to indicate
                                  whether to create a SubnetSet or not as the primary
                                  network. If not set, the default is true.
                                type: boolean
                            type: object
                            x-kubernetes-validations:
                            - message: createSubnetSet value cannot be changed after
                                creation
                              rule: has(self.createSubnetSet) == has(oldSelf.createSubnetSet)
                                && self.createSubnetSet == oldSelf.createSubnetSet
                        type: object
                        x-kubernetes-validations:
                        - message: field 'nsxVPC' cannot be added or removed after
                            creation
                          rule: has(self.nsxVPC) == has(oldSelf.nsxVPC)
                    type: object
                    x-kubernetes-validations:
                    - message: field 'network' cannot be added or removed after creation
                      rule: has(self.network) == has(oldSelf.network)
                required:
                - spec
                type: object
            required:
            - template
            type: object
        type: object
    served: true
    storage: false
  - name: v1beta2
    schema:
      openAPIV3Schema:
        description: VSphereClusterTemplate is the Schema for the vsphereclustertemplates
          API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec is the desired state of VSphereClusterTemplate.
            properties:
              template:
                description: template defines the desired state of VSphereClusterTemplate.
                properties:
                  spec:
                    description: spec is the desired state of VSphereClusterTemplateResource.
                    properties:
                      controlPlaneEndpoint:
                        description: controlPlaneEndpoint represents the endpoint
                          used to communicate with the control plane.
                        properties:
                          host:
                            description: host is the hostname on which the API server
                              is serving.
                            maxLength: 512
                            type: string
                          port:
                            description: port is the port on which the API server
                              is serving.
                            format: int32
                            type: integer
                        type: object
                      network:
                        description: network defines the network configuration for
                          the cluster with different network providers.
                        minProperties: 1
                        properties:
                          nsxVPC:
                            description: nsxVPC defines the configuration when the
                              network provider is NSX-VPC.
                            minProperties: 1
                            properties:
                              createSubnetSet:
                                description: createSubnetSet is a flag to indicate
                                  whether to create a SubnetSet or not as the primary
                                  network. If not set, the default is true.
                                type: boolean
                            type: object
                            x-kubernetes-validations:
                            - message: createSubnetSet value cannot be changed after
                                creation
                              rule: has(self.createSubnetSet) == has(oldSelf.createSubnetSet)
                                && self.createSubnetSet == oldSelf.createSubnetSet
                        type: object
                        x-kubernetes-validations:
                        - message: field 'nsxVPC' cannot be added or removed after
                            creation
                          rule: has(self.nsxVPC) == has(oldSelf.nsxVPC)
                    type: object
                    x-kubernetes-validations:
                    - message: field 'network' cannot be added or removed after creation
                      rule: has(self.network) == has(oldSelf.network)
                required:
                - spec
                type: object
            required:
            - template
            type: object
        type: object
    served: true
    storage: true
