apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Adds namespace to all resources.
namespace: capv-system

namePrefix: capv-

commonLabels:
  cluster.x-k8s.io/provider: "infrastructure-vsphere"
  cluster.x-k8s.io/v1beta1: v1beta1
  cluster.x-k8s.io/v1beta2: v1beta2
resources:
  - ../base
  - crd/bases/vmware.infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  - crd/bases/vmware.infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  - crd/bases/vmware.infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  - crd/bases/vmware.infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
  - crd/bases/vmware.infrastructure.cluster.x-k8s.io_providerserviceaccounts.yaml
  - ./webhook

patches:
  # [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
  # patches here are for enabling the conversion webhook for each CRD
  - path: crd/patches/webhook_in_providerserviceaccounts.yaml
  - path: crd/patches/webhook_in_vsphereclusters.yaml
  - path: crd/patches/webhook_in_vsphereclustertemplates.yaml
  - path: crd/patches/webhook_in_vspheremachines.yaml
  - path: crd/patches/webhook_in_vspheremachinetemplates.yaml
  # +kubebuilder:scaffold:crdkustomizewebhookpatch

  # [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
  # patches here are for enabling the CA injection for each CRD
  - path: crd/patches/cainjection_in_providerserviceaccounts.yaml
  - path: crd/patches/cainjection_in_vsphereclusters.yaml
  - path: crd/patches/cainjection_in_vsphereclustertemplates.yaml
  - path: crd/patches/cainjection_in_vspheremachines.yaml
  - path: crd/patches/cainjection_in_vspheremachinetemplates.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
  - kustomizeconfig.yaml

vars:
  - name: CERTIFICATE_NAMESPACE # namespace of the certificate CR
    objref:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: serving-cert # this name should match the one in certificate.yaml
    fieldref:
      fieldpath: metadata.namespace
  - name: CERTIFICATE_NAME
    objref:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: serving-cert # this name should match the one in certificate.yaml
  - name: SERVICE_NAMESPACE # namespace of the service
    objref:
      kind: Service
      version: v1
      name: webhook-service
    fieldref:
      fieldpath: metadata.namespace
  - name: SERVICE_NAME
    objref:
      kind: Service
      version: v1
      name: webhook-service
