---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.10.0
  creationTimestamp: null
  name: virtualmachineimages.vmoperator.vmware.com
spec:
  group: vmoperator.vmware.com
  names:
    kind: VirtualMachineImage
    listKind: VirtualMachineImageList
    plural: virtualmachineimages
    shortNames:
    - vmi
    - vmimage
    singular: virtualmachineimage
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.providerRef.name
      name: Provider-Name
      type: string
    - jsonPath: .status.contentLibraryRef.name
      name: Content-Library-Name
      type: string
    - jsonPath: .status.imageName
      name: Image-Name
      type: string
    - jsonPath: .spec.productInfo.version
      name: Version
      type: string
    - jsonPath: .spec.osInfo.type
      name: Os-Type
      type: string
    - jsonPath: .spec.type
      name: Format
      type: string
    - jsonPath: .status.imageSupported
      name: Image-Supported
      priority: 1
      type: boolean
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: VirtualMachineImage is the Schema for the virtualmachineimages
          API A VirtualMachineImage represents a VirtualMachine image (e.g. VM template)
          that can be used as the base image for creating a VirtualMachine instance.  The
          VirtualMachineImage is a required field of the VirtualMachine spec.  Currently,
          VirtualMachineImages are immutable to end users.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: VirtualMachineImageSpec defines the desired state of VirtualMachineImage.
            properties:
              hwVersion:
                description: HardwareVersion describes the virtual hardware version
                  of the image
                format: int32
                type: integer
              imageID:
                description: ImageID is a unique identifier exposed by the provider
                  of this VirtualMachineImage.
                type: string
              imageSourceType:
                description: ImageSourceType describes the type of content source
                  of the VirtualMachineImage.  The only Content Source supported currently
                  is the vSphere Content Library.
                type: string
              osInfo:
                description: OSInfo describes the attributes of the VirtualMachineImage
                  relating to the Operating System contained in the image.
                properties:
                  type:
                    description: Type typically describes the type of the guest operating
                      system.
                    type: string
                  version:
                    description: Version typically describes the version of the guest
                      operating system.
                    type: string
                type: object
              ovfEnv:
                additionalProperties:
                  description: OvfProperty describes information related to a user
                    configurable property element that is supported by VirtualMachineImage
                    and can be customized during VirtualMachine creation.
                  properties:
                    default:
                      description: Default describes the default value of the ovf
                        key.
                      type: string
                    description:
                      description: Description contains the value of the OVF property's
                        optional "Description" element.
                      type: string
                    key:
                      description: Key describes the key of the ovf property.
                      type: string
                    label:
                      description: Label contains the value of the OVF property's
                        optional "Label" element.
                      type: string
                    type:
                      description: Type describes the type of the ovf property.
                      type: string
                  required:
                  - key
                  - type
                  type: object
                description: OVFEnv describes the user configurable customization
                  parameters of the VirtualMachineImage.
                type: object
              productInfo:
                description: ProductInfo describes the attributes of the VirtualMachineImage
                  relating to the product contained in the image.
                properties:
                  fullVersion:
                    description: FullVersion typically describes a long-form version
                      of the image.
                    type: string
                  product:
                    description: Product typically describes the type of product contained
                      in the image.
                    type: string
                  vendor:
                    description: Vendor typically describes the name of the vendor
                      that is producing the image.
                    type: string
                  version:
                    description: Version typically describes a short-form version
                      of the image.
                    type: string
                type: object
              providerRef:
                description: ProviderRef is a reference to a content provider object
                  that describes a provider.
                properties:
                  apiVersion:
                    description: API version of the referent.
                    type: string
                  kind:
                    description: Kind is the type of resource being referenced.
                    type: string
                  name:
                    description: Name is the name of resource being referenced.
                    type: string
                  namespace:
                    description: Namespace of the resource being referenced. If empty,
                      cluster scoped resource is assumed.
                    type: string
                required:
                - kind
                - name
                type: object
              type:
                description: Type describes the type of the VirtualMachineImage. Currently,
                  the only supported image is "OVF"
                type: string
            required:
            - imageID
            - providerRef
            - type
            type: object
          status:
            description: VirtualMachineImageStatus defines the observed state of VirtualMachineImage.
            properties:
              conditions:
                description: Conditions describes the current condition information
                  of the VirtualMachineImage object. e.g. if the OS type is supported
                  or image is supported by VMService
                items:
                  description: Condition defines an observation of a VM Operator API
                    resource operational state.
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.
                        If that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    severity:
                      description: Severity provides an explicit classification of
                        Reason code, so the users or machines can immediately understand
                        the current situation and act accordingly. The Severity field
                        MUST be set only when Status=False.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to disambiguate
                        is important.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              contentLibraryRef:
                description: ContentLibraryRef is a reference to the source ContentLibrary/ClusterContentLibrary
                  resource.
                properties:
                  apiGroup:
                    description: APIGroup is the group for the resource being referenced.
                      If APIGroup is not specified, the specified Kind must be in
                      the core API group. For any other third-party types, APIGroup
                      is required.
                    type: string
                  kind:
                    description: Kind is the type of resource being referenced
                    type: string
                  name:
                    description: Name is the name of resource being referenced
                    type: string
                required:
                - kind
                - name
                type: object
                x-kubernetes-map-type: atomic
              contentVersion:
                description: ContentVersion describes the observed content version
                  of this VirtualMachineImage that was last successfully synced with
                  the vSphere content library item.
                type: string
              imageName:
                description: ImageName describes the display name of this VirtualMachineImage.
                type: string
              imageSupported:
                description: 'ImageSupported indicates whether the VirtualMachineImage
                  is supported by VMService. A VirtualMachineImage is supported by
                  VMService if the following conditions are true: - VirtualMachineImageV1Alpha1CompatibleCondition'
                type: boolean
              internalId:
                description: Deprecated
                type: string
              powerState:
                description: Deprecated
                type: string
              uuid:
                description: Deprecated
                type: string
            required:
            - internalId
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
