---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
  name: virtualmachinesnapshots.vmoperator.vmware.com
spec:
  group: vmoperator.vmware.com
  names:
    kind: VirtualMachineSnapshot
    listKind: VirtualMachineSnapshotList
    plural: virtualmachinesnapshots
    shortNames:
    - vmsnapshot
    singular: virtualmachinesnapshot
  scope: Namespaced
  versions:
  - name: v1alpha5
    schema:
      openAPIV3Schema:
        description: VirtualMachineSnapshot is the schema for the virtualmachinesnapshot
          API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: VirtualMachineSnapshotSpec defines the desired state of VirtualMachineSnapshot.
            properties:
              description:
                description: Description represents a description of the snapshot.
                type: string
              memory:
                description: |-
                  Memory represents whether the snapshot includes the VM's
                  memory. If true, a dump of the internal state of the virtual
                  machine (a memory dump) is included in the snapshot. Memory
                  snapshots consume time and resources and thus, take longer to
                  create.
                  The virtual machine must support this capability.
                  When set to false, the power state of the snapshot is set to
                  false.
                  For a VM in suspended state, memory is always included
                  in the snashot.
                type: boolean
              quiesce:
                description: |-
                  Quiesce represents the spec used for granular control over
                  quiesce details. If quiesceSpec is set and the virtual machine
                  is powered on when the snapshot is taken, VMware Tools is used
                  to quiesce the file system in the virtual machine. This assures
                  that a disk snapshot represents a consistent state of the guest
                  file systems. If the virtual machine is powered off or VMware
                  Tools are not available, the quiesce spec is ignored.
                properties:
                  timeout:
                    description: |-
                      Timeout represents the maximum time in minutes for snapshot
                      operation to be performed on the virtual machine. The timeout
                      can not be less than 5 minutes or more than 240 minutes.
                    type: string
                type: object
              vmName:
                description: |-
                  VMName represents the name of the virtual machine for which the
                  snapshot is requested.
                type: string
            type: object
          status:
            description: VirtualMachineSnapshotStatus defines the observed state of
              VirtualMachineSnapshot.
            properties:
              children:
                description: |-
                  Children represents the snapshots for which this snapshot is
                  the parent.
                items:
                  properties:
                    name:
                      description: |-
                        Name is the name of the snapshot resource.  This field is only set
                        for managed snapshots.
                      type: string
                    type:
                      default: Managed
                      description: |-
                        Type describes the type of the snapshot reference.

                        Possible values are: Managed, Unmanaged
                      enum:
                      - Managed
                      - Unmanaged
                      type: string
                  required:
                  - name
                  - type
                  type: object
                type: array
              conditions:
                description: Conditions describes the observed conditions of the VirtualMachine.
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              powerState:
                description: |-
                  PowerState represents the observed power state of the virtual
                  machine when the snapshot was taken.
                enum:
                - PoweredOff
                - PoweredOn
                - Suspended
                type: string
              quiesced:
                description: |-
                  Quiesced represents whether or not the snapshot was created
                  with the quiesce option to ensure a snapshot with a consistent
                  state of the guest file system.
                type: boolean
              storage:
                description: |-
                  Storage describes the observed amount of storage used by a
                  VirtualMachineSnapshot, including the space for FCDs.
                properties:
                  requested:
                    description: |-
                      Requested describes the observed amount of storage requested by a
                      VirtualMachineSnapshot. It's a list of requested storage for each
                      storage class.
                      Since a snapshot can have multiple PVCs, it can point to multiple storage
                      classes.
                    items:
                      description: |-
                        VirtualMachineSnapshotStorageStatusRequested describes the observed amount of
                        storage requested by a VirtualMachineSnapshot for a storage class.
                      properties:
                        storageClass:
                          description: StorageClass is the name of the storage class.
                          type: string
                        total:
                          anyOf:
                          - type: integer
                          - type: string
                          description: |-
                            Total describes the total storage space requested by a
                            VirtualMachineSnapshot for the storage class.
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                      required:
                      - storageClass
                      - total
                      type: object
                    type: array
                  used:
                    anyOf:
                    - type: integer
                    - type: string
                    description: |-
                      Used describes the observed amount of storage used by a
                      VirtualMachineSnapshot, except the space for FCDs.
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                type: object
              uniqueID:
                description: |-
                  UniqueID describes a unique identifier provider by the backing
                  infrastructure (e.g., vSphere) that can be used to distinguish
                  this snapshot from other snapshots of this virtual machine.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
