
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.4
  creationTimestamp: null
  name: haproxyloadbalancers.infrastructure.cluster.x-k8s.io
spec:
  group: infrastructure.cluster.x-k8s.io
  names:
    kind: HAProxyLoadBalancer
    listKind: HAProxyLoadBalancerList
    plural: haproxyloadbalancers
    singular: haproxyloadbalancer
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: HAProxyLoadBalancer is the Schema for the haproxyloadbalancers
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: HAProxyLoadBalancerSpec defines the desired state of HAProxyLoadBalancer.
          properties:
            ports:
              description: Ports is a list of one or more pairs of ports on which
                the load balancer listens for incoming traffic and the ports on the
                backend to which the traffic is transmitted.
              items:
                description: LoadBalancerPort defines the pair of frontend and backend
                  ports used by the load balancer.
                properties:
                  backend:
                    description: Backend is a list of the backend servers and ports
                      to which the load balancer transmits traffic from the frontend
                      port.
                    items:
                      description: LoadBalancerBackendPort represents a reachable
                        backend resource for a load balancer.
                      properties:
                        host:
                          description: The hostname on which the backend server is
                            serving.
                          type: string
                        port:
                          description: The port on which the backend server is serving.
                          format: int32
                          type: integer
                      required:
                      - host
                      - port
                      type: object
                    type: array
                  frontend:
                    description: Frontend is the port on which a load balancer listens
                      for incoming traffic.
                    format: int32
                    type: integer
                required:
                - frontend
                type: object
              type: array
            virtualMachineConfiguration:
              description: VirtualMachineConfiguration is optional information used
                to deploy a new load balancer VM. If omitted then the HAProxy API
                configuration must point to an existing load balancer.
              properties:
                cloneMode:
                  description: CloneMode specifies the type of clone operation. The
                    LinkedClone mode is only support for templates that have at least
                    one snapshot. If the template has no snapshots, then CloneMode
                    defaults to FullClone. When LinkedClone mode is enabled the DiskGiB
                    field is ignored as it is not possible to expand disks of linked
                    clones. Defaults to LinkedClone, but fails gracefully to FullClone
                    if the source of the clone operation has no snapshots.
                  type: string
                datacenter:
                  description: Datacenter is the name or inventory path of the datacenter
                    in which the virtual machine is created/located.
                  type: string
                datastore:
                  description: Datastore is the name or inventory path of the datastore
                    in which the virtual machine is created/located.
                  type: string
                diskGiB:
                  description: DiskGiB is the size of a virtual machine's disk, in
                    GiB. Defaults to the eponymous property value in the template
                    from which the virtual machine is cloned.
                  format: int32
                  type: integer
                folder:
                  description: Folder is the name or inventory path of the folder
                    in which the virtual machine is created/located.
                  type: string
                memoryMiB:
                  description: MemoryMiB is the size of a virtual machine's memory,
                    in MiB. Defaults to the eponymous property value in the template
                    from which the virtual machine is cloned.
                  format: int64
                  type: integer
                network:
                  description: Network is the network configuration for this machine's
                    VM.
                  properties:
                    devices:
                      description: Devices is the list of network devices used by
                        the virtual machine. TODO(akutz) Make sure at least one network
                        matches the             ClusterSpec.CloudProviderConfiguration.Network.Name
                      items:
                        description: NetworkDeviceSpec defines the network configuration
                          for a virtual machine's network device.
                        properties:
                          dhcp4:
                            description: DHCP4 is a flag that indicates whether or
                              not to use DHCP for IPv4 on this device. If true then
                              IPAddrs should not contain any IPv4 addresses.
                            type: boolean
                          dhcp6:
                            description: DHCP6 is a flag that indicates whether or
                              not to use DHCP for IPv6 on this device. If true then
                              IPAddrs should not contain any IPv6 addresses.
                            type: boolean
                          gateway4:
                            description: Gateway4 is the IPv4 gateway used by this
                              device. Required when DHCP4 is false.
                            type: string
                          gateway6:
                            description: Gateway4 is the IPv4 gateway used by this
                              device. Required when DHCP6 is false.
                            type: string
                          ipAddrs:
                            description: IPAddrs is a list of one or more IPv4 and/or
                              IPv6 addresses to assign to this device. Required when
                              DHCP4 and DHCP6 are both false.
                            items:
                              type: string
                            type: array
                          macAddr:
                            description: MACAddr is the MAC address used by this device.
                              It is generally a good idea to omit this field and allow
                              a MAC address to be generated. Please note that this
                              value must use the VMware OUI to work with the in-tree
                              vSphere cloud provider.
                            type: string
                          mtu:
                            description: MTU is the deviceâ€™s Maximum Transmission
                              Unit size in bytes.
                            format: int64
                            type: integer
                          nameservers:
                            description: Nameservers is a list of IPv4 and/or IPv6
                              addresses used as DNS nameservers. Please note that
                              Linux allows only three nameservers (https://linux.die.net/man/5/resolv.conf).
                            items:
                              type: string
                            type: array
                          networkName:
                            description: NetworkName is the name of the vSphere network
                              to which the device will be connected.
                            type: string
                          routes:
                            description: Routes is a list of optional, static routes
                              applied to the device.
                            items:
                              description: NetworkRouteSpec defines a static network
                                route.
                              properties:
                                metric:
                                  description: Metric is the weight/priority of the
                                    route.
                                  format: int32
                                  type: integer
                                to:
                                  description: To is an IPv4 or IPv6 address.
                                  type: string
                                via:
                                  description: Via is an IPv4 or IPv6 address.
                                  type: string
                              required:
                              - metric
                              - to
                              - via
                              type: object
                            type: array
                          searchDomains:
                            description: SearchDomains is a list of search domains
                              used when resolving IP addresses with DNS.
                            items:
                              type: string
                            type: array
                        required:
                        - networkName
                        type: object
                      type: array
                    preferredAPIServerCidr:
                      description: PreferredAPIServeCIDR is the preferred CIDR for
                        the Kubernetes API server endpoint on this machine
                      type: string
                    routes:
                      description: Routes is a list of optional, static routes applied
                        to the virtual machine.
                      items:
                        description: NetworkRouteSpec defines a static network route.
                        properties:
                          metric:
                            description: Metric is the weight/priority of the route.
                            format: int32
                            type: integer
                          to:
                            description: To is an IPv4 or IPv6 address.
                            type: string
                          via:
                            description: Via is an IPv4 or IPv6 address.
                            type: string
                        required:
                        - metric
                        - to
                        - via
                        type: object
                      type: array
                  required:
                  - devices
                  type: object
                numCPUs:
                  description: NumCPUs is the number of virtual processors in a virtual
                    machine. Defaults to the eponymous property value in the template
                    from which the virtual machine is cloned.
                  format: int32
                  type: integer
                numCoresPerSocket:
                  description: NumCPUs is the number of cores among which to distribute
                    CPUs in this virtual machine. Defaults to the eponymous property
                    value in the template from which the virtual machine is cloned.
                  format: int32
                  type: integer
                resourcePool:
                  description: ResourcePool is the name or inventory path of the resource
                    pool in which the virtual machine is created/located.
                  type: string
                server:
                  description: Server is the IP address or FQDN of the vSphere server
                    on which the virtual machine is created/located.
                  type: string
                snapshot:
                  description: Snapshot is the name of the snapshot from which to
                    create a linked clone. This field is ignored if LinkedClone is
                    not enabled. Defaults to the source's current snapshot.
                  type: string
                template:
                  description: Template is the name or inventory path of the template
                    used to clone the virtual machine.
                  type: string
              required:
              - network
              - template
              type: object
          type: object
        status:
          description: HAProxyLoadBalancerStatus defines the observed state of HAProxyLoadBalancer.
          properties:
            address:
              description: "Address is the IP address or DNS name of the load balancer.
                \n This field is required as part of the Portable Load Balancer model
                and is inspected via an unstructured reader by other controllers to
                determine the status of the load balancer."
              type: string
            ready:
              description: "Ready indicates whether or not the load balancer is ready.
                \n This field is required as part of the Portable Load Balancer model
                and is inspected via an unstructured reader by other controllers to
                determine the status of the load balancer."
              type: boolean
          type: object
      type: object
  version: v1alpha3
  versions:
  - name: v1alpha3
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
